### ISSUE TITLE
Ai maakt niet optimale zet bij keuze win blokeren en winnen

### ISSUE THREAD

**Issue by MichelGerding** [HeadTriXz/Project-ISY#6]
bij het maken van een move door de ai blokkeert hij terwijl hij ook kan winnen.

![Screen_Recording_2022-11-04_at_14 47 56](https://user-images.githubusercontent.com/45393586/200000616-ffd5775f-1456-449a-8ecd-1c411116a446.gif)

**Comment by JonaVDM** [comment]
Link naar trello card: https://trello.com/c/UmcxpBu8/73-fix-dit-see-attachment
